# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.19)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget PDFHummus::Zlib PDFHummus::FreeType PDFHummus::LibAesgm PDFHummus::LibJpeg PDFHummus::LibTiff PDFHummus::LibPng PDFHummus::PDFWriter)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target PDFHummus::Zlib
add_library(PDFHummus::Zlib STATIC IMPORTED)

set_target_properties(PDFHummus::Zlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/Zlib"
)

# Create imported target PDFHummus::FreeType
add_library(PDFHummus::FreeType STATIC IMPORTED)

set_target_properties(PDFHummus::FreeType PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "FT2_BUILD_LIBRARY=1;FT_CONFIG_OPTION_SYSTEM_ZLIB=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/FreeType/include"
  INTERFACE_LINK_LIBRARIES "PDFHummus::Zlib"
)

# Create imported target PDFHummus::LibAesgm
add_library(PDFHummus::LibAesgm STATIC IMPORTED)

set_target_properties(PDFHummus::LibAesgm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/LibAesgm"
)

# Create imported target PDFHummus::LibJpeg
add_library(PDFHummus::LibJpeg STATIC IMPORTED)

set_target_properties(PDFHummus::LibJpeg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/LibJpeg"
)

# Create imported target PDFHummus::LibTiff
add_library(PDFHummus::LibTiff STATIC IMPORTED)

set_target_properties(PDFHummus::LibTiff PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "_CRT_SECURE_NO_DEPRECATE=1;AVOID_WIN32_FILEIO=1;CHECK_JPEG_YCBCR_SUBSAMPLING=1;DEFAULT_EXTRASAMPLE_AS_ALPHA=1;STRIPCHOP_DEFAULT=TIFF_STRIPCHOP;STRIP_SIZE_DEFAULT=8192;PIXARLOG_SUPPORT=1;ZIP_SUPPORT=1;LOGLUV_SUPPORT=1;NEXT_SUPPORT=1;THUNDER_SUPPORT=1;LZW_SUPPORT=1;PACKBITS_SUPPORT=1;CCITT_SUPPORT=1;TIF_PLATFORM_CONSOLE=1;FILLODER_LSB2MSB=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/LibTiff"
  INTERFACE_LINK_LIBRARIES "PDFHummus::Zlib"
)

# Create imported target PDFHummus::LibPng
add_library(PDFHummus::LibPng STATIC IMPORTED)

set_target_properties(PDFHummus::LibPng PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/LibPng"
  INTERFACE_LINK_LIBRARIES "PDFHummus::Zlib"
)

# Create imported target PDFHummus::PDFWriter
add_library(PDFHummus::PDFWriter STATIC IMPORTED)

set_target_properties(PDFHummus::PDFWriter PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/PDFWriter"
  INTERFACE_LINK_LIBRARIES "PDFHummus::Zlib;PDFHummus::FreeType;PDFHummus::LibAesgm;PDFHummus::LibJpeg;PDFHummus::LibTiff;PDFHummus::LibPng"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/PDFHummusTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
