# Define the name of the workflow
name: DocSpeak lib Tests

# Trigger the workflow on push events
on: push

# Define the jobs
jobs:
  # Clone and build the repository with CMake
  build:
    # Use a Windows VM
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          
      - name: Build the tests
        shell: pwsh
        run: |
          .\test.ps1 --build-only

      # Upload the build artifacts for the next job
      - name: Upload Build Bin Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_bin
          path: .\build\bin\

      - name: Upload Test Assets Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test_assets
          path: .\build\DocSpeak\tests

  # Run some unit tests
  unit-test:
    # Use a Windows VM
    runs-on: windows-latest
    # Only run this job if the previous one succeeded
    needs: build
    steps:
      # Download the build artifacts from the previous job
      - name: Download Build Bin artifacts
        uses: actions/download-artifact@v2
        with:
          name: build_bin
          path: .\build\bin\

      - name: Download Test Assets artifacts
        uses: actions/download-artifact@v2
        with:
          name: test_assets
          path: .\build\DocSpeak\tests

      - name: Run the Tests
        run:  .\test.ps1 --run-tests
          
      - name: Upload Test Log
        uses: actions/upload-artifact@v2
        with:
          name: test_log
          path: .\build\bin\docspeak.log

      - name: Upload Test Details
        uses: actions/upload-artifact@v2
        with:
          name: test_details
          path: .\build\bin\test_detail.xml
