# Define the name of the workflow
name: Unit Tests

# Trigger the workflow on push events
on: push

# Define the jobs
jobs:
  # Clone and build the repository with CMake
  build:
    # Use a Windows VM
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build the tests
        run: |
          pwsh .\build.ps1 --build-only
      # Upload the build artifacts for the next job
      - name: Upload Build Bin Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_bin
          path: .\build\bin\
      - name: Upload CTest Cmake configuration Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ctest_config
          path: .\build\DocSpeak\tests

  # Run some unit tests
  test:
    # Use a Windows VM
    runs-on: windows-latest
    # Only run this job if the previous one succeeded
    needs: build
    steps:
      # Download the build artifacts from the previous job
      - name: Download Build Bin artifacts
        uses: actions/download-artifact@v2
        with:
          name: build_bin
          path: .\build\bin\
      - name: Download Ctest Config artifacts
        uses: actions/download-artifact@v2
        with:
          name: ctest_config
          path: .\build\DocSpeak\tests
      - name: Run the Tests
        run: |
          cd build/bin
          ctest --test-dir "..\DocSpeak\tests" --output-on-failure
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: |
            .\build\bin\
            .\build\DocSpeak\tests
